// This file is auto-generated by @tanstack/router-vite-plugin
// Do not edit this file manually
import { RootRoute } from '@tanstack/react-router'
import { RootComponent } from './routes/__root'

const rootRoute = new RootRoute({ component: RootComponent })

export const routeTree = rootRoute
